// F6 — korpusdagi `ikonka` maydoni (masalan "bulb", "kite") uchun ko'rinadigan
// emoji belgisiga moslashtirish jadvali. Bu sof ma'lumot fayli — hech qanday
// server siri yoki tashqi chaqiruv yo'q, shuning uchun ham server, ham
// klient komponentlarida bemalol import qilinadi.
//
// MUHIM: faqat 2018-yilgacha (Unicode ≤11) tasdiqlangan, keng tarqalgan
// emojilar ishlatiladi. 2020-2021 (Unicode 13-14) belgilari — masalan
// "igna" (🪡) — ko'plab Windows qurilmalarida hali ham bo'sh katakcha
// bo'lib ko'rinadi (foydalanuvchi xabar berdi). Shu sabab "igna" bilan bir
// davrda qo'shilgan barcha belgilar eskiroq, xavfsizroq muqobillarga
// almashtirildi.

const IKONKA_EMOJI: Record<string, string> = {
  airplane: "✈️",
  almond: "🥜",
  ant: "🐜",
  apple: "🍎",
  apricot: "🍑",
  ball: "⚽",
  bat: "🦇",
  beans: "🌱",
  beet: "🍠",
  beetle: "🐞",
  bell: "🔔",
  bicycle: "🚲",
  blanket: "🛏️",
  book: "📖",
  boots: "👢",
  bread: "🍞",
  bulb: "💡",
  butterfly: "🦋",
  cabbage: "🥬",
  camel: "🐫",
  candle: "🕯️",
  car: "🚗",
  carrot: "🥕",
  cat: "🐱",
  chickpea: "🌱",
  chimney: "🏠",
  clock: "🕐",
  clothes: "👕",
  cloud: "☁️",
  corn: "🌽",
  cotton: "☁️",
  cow: "🐄",
  cucumber: "🥒",
  cup: "☕",
  dog: "🐶",
  doll: "🧸",
  donkey: "🐴",
  door: "🚪",
  drum: "🥁",
  dumpling: "🥟",
  dutar: "🪕",
  ear: "👂",
  earth: "🌍",
  earthquake: "💥",
  egg: "🥚",
  electricity: "⚡",
  elephant: "🐘",
  elevator: "⬆️",
  eye: "👁️",
  eyebrow: "🤨",
  fig: "🍈",
  finger: "☝️",
  fish: "🐟",
  fly: "🐛",
  fox: "🦊",
  fridge: "🧊",
  frog: "🐸",
  gloves: "🧤",
  goat: "🐐",
  gopher: "🐿️",
  grape: "🍇",
  grasshopper: "🦗",
  gum: "🍬",
  head: "🙂",
  hedgehog: "🦔",
  hoe: "⛏️",
  horn: "📯",
  horse: "🐴",
  ice: "🧊",
  jida: "🍇",
  jug: "🏺",
  key: "🔑",
  kite: "🎏",
  ladder: "🧗",
  ladle: "🥄",
  leg: "🦵",
  lizard: "🦎",
  lock: "🔒",
  magpie: "🐦",
  matches: "🔥",
  melon: "🍈",
  milk: "🥛",
  mill: "⚙️",
  mirror: "🔍",
  moon: "🌙",
  "mosquito-net": "🦟",
  mouse: "🐭",
  mouth: "👄",
  "mung-bean": "🌱",
  nail: "🔩",
  needle: "🧵",
  nightingale: "🐦",
  nose: "👃",
  notebook: "📓",
  onion: "🧅",
  owl: "🦉",
  paper: "📄",
  peach: "🍑",
  pen: "🖊️",
  pencil: "✏️",
  pepper: "🌶️",
  pliers: "🔧",
  pomegranate: "🔴",
  pool: "🏊",
  porridge: "🥣",
  pot: "🍲",
  pumpkin: "🎃",
  quince: "🍐",
  rabbit: "🐰",
  radio: "📻",
  rice: "🍚",
  ring: "💍",
  rocket: "🚀",
  rooster: "🐓",
  samovar: "🍵",
  saw: "⚒️",
  school: "🏫",
  scissors: "✂️",
  scorpion: "🦂",
  shadow: "🌑",
  sheep: "🐑",
  sieve: "🕸️",
  silkworm: "🐛",
  sky: "🌌",
  snake: "🐍",
  snow: "❄️",
  sparrow: "🐦",
  spider: "🕷️",
  spindle: "🧵",
  spoon: "🥄",
  star: "⭐",
  stork: "🦢",
  sugar: "🍬",
  sun: "☀️",
  sunflower: "🌻",
  swallow: "🐦",
  tandoor: "🔥",
  "tape-recorder": "📼",
  tea: "🍵",
  teapot: "🍵",
  thought: "💭",
  thread: "🧵",
  tiger: "🐯",
  tongue: "👅",
  tooth: "🦷",
  train: "🚂",
  trumpet: "🎺",
  tubeteika: "🧢",
  turnip: "🥔",
  turtle: "🐢",
  tv: "📺",
  walnut: "🌰",
  "water-drop": "💧",
  watermelon: "🍉",
  well: "🕳️",
  wheat: "🌾",
  wind: "💨",
  wolf: "🐺",
  "wool-comb": "🧶",
  yogurt: "🥛",
};

/** Berilgan ikonka nomi uchun emoji qaytaradi; noma'lum nom kelsa ham
 * ilova qulamasligi uchun neytral zaxira belgi beriladi. */
export function ikonkaEmoji(nomi: string): string {
  return IKONKA_EMOJI[nomi] ?? "🎁";
}
